"""add lastname to employee33

Revision ID: 29ad26b1da70
Revises: 4ce01e708c0d
Create Date: 2024-07-22 15:17:37.635026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29ad26b1da70'
down_revision: Union[str, None] = '4ce01e708c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees33')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("employees33")
    pass
    # ### end Alembic commands ###