"""adding productCode column to product table

Revision ID: 9ecf12c7bfcb
Revises: e56c5c8dc847
Create Date: 2024-07-22 17:25:21.421442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ecf12c7bfcb'
down_revision: Union[str, None] = 'e56c5c8dc847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productCode',sa.String(length=5), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'product_code_length_check',
        'products',
        'length(productCode) = 5'
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_code_length_check', 'products', type_='check')
    # Drop the column
    op.drop_column('products', 'productCode')
    # ### end Alembic commands ###
